import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generatePDFReport = (summary, budget, expenses, month, year) => {
  const doc = new jsPDF();
  const monthName = new Date(year, month - 1).toLocaleString('default', { month: 'long' });

  // Header
  doc.setFillColor(102, 126, 234);
  doc.rect(0, 0, 210, 35, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('FinanceTracker - Monthly Report', 14, 15);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`${monthName} ${year}`, 14, 26);

  // Summary Stats
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 14, 50);

  const summaryData = [
    ['Total Spent', `Rs. ${summary?.total?.toFixed(2) || '0.00'}`],
    ['Monthly Budget', budget ? `Rs. ${budget.amount.toFixed(2)}` : 'Not Set'],
    ['Remaining Budget', budget ? `Rs. ${(budget.amount - (summary?.total || 0)).toFixed(2)}` : 'N/A'],
    ['Total Expenses', `${expenses.length} transactions`],
    ['Needs', `Rs. ${summary?.byType?.need?.toFixed(2) || '0.00'}`],
    ['Wants', `Rs. ${summary?.byType?.want?.toFixed(2) || '0.00'}`],
  ];

  autoTable(doc, {
    startY: 55,
    head: [['Metric', 'Value']],
    body: summaryData,
    theme: 'grid',
    headStyles: { fillColor: [102, 126, 234] },
    columnStyles: { 1: { halign: 'right' } }
  });

  // Category Breakdown
  const categoryY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Spending by Category', 14, categoryY);

  const categoryData = Object.entries(summary?.byCategory || {})
    .sort((a, b) => b[1] - a[1])
    .map(([cat, amt]) => [cat, `Rs. ${amt.toFixed(2)}`]);

  autoTable(doc, {
    startY: categoryY + 5,
    head: [['Category', 'Amount']],
    body: categoryData,
    theme: 'grid',
    headStyles: { fillColor: [102, 126, 234] },
    columnStyles: { 1: { halign: 'right' } }
  });

  // Expense List
  const expenseY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Expense Details', 14, expenseY);

  const expenseData = expenses.map(e => [
    new Date(e.date).toLocaleDateString('en-IN'),
    e.description,
    e.category,
    e.type === 'need' ? 'Need' : 'Want',
    `Rs. ${e.amount.toFixed(2)}`
  ]);

  autoTable(doc, {
    startY: expenseY + 5,
    head: [['Date', 'Description', 'Category', 'Type', 'Amount']],
    body: expenseData,
    theme: 'grid',
    headStyles: { fillColor: [102, 126, 234] },
    columnStyles: { 4: { halign: 'right' } }
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(`Generated by FinanceTracker | Page ${i} of ${pageCount}`, 14, 290);
  }

  doc.save(`FinanceTracker_${monthName}_${year}.pdf`);
};